#include "fonts/NotoSansMono_Bold_100.h"
#include "fonts/NotoSansMono_Bold_14.h"
#include "fonts/NotoSansMono_Bold_20.h"
#include "fonts/NotoSansMono_Bold_50.h"
#include "fonts/NotoSansMono_Regular_12.h"
#include "fonts/NotoSansMono_Regular_30.h"
#include "fonts/NotoSansMono_Regular_50.h"
